[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "chainlit==1.3.2",
    "markdown>=3.8",
    "python-markdown-math==0.8",
]
